---
substitutions:
  friendly_name: Back Porch
  name: back-porch-light
  ip: '10.0.1.250'

packages:
  base: !include packages/base.yaml
  devices: !include packages/devices/shelly-duo.yaml
  components: !include packages/components/cwww-light.yaml
...
