---
substitutions:
  friendly_name: Back Porch Light
  name: back-porch-light
  ip: '10.0.1.250'

packages:
  base: !include packages/base.yaml
  device: !include packages/devices/shelly-duo.yaml
  component: !include
    file: packages/components/cwww-light.yaml
    vars:
      cold_white: cold_white
      warm_white: warm_white
...
