---
substitutions:
  friendly_name: Dining Room 2
  name: dining-room-light-2
  ip: '10.0.1.146'

packages:
  base: !include packages/base.yaml
  device: !include packages/devices/shelly-duo.yaml
  component: !include packages/components/cwww-light.yaml
...
