---
substitutions:
  friendly_name: Dining Room 1
  name: dining-room-light-1
  ip: '10.0.1.233'

packages:
  base: !include packages/base.yaml
  devices: !include packages/devices/shelly-duo.yaml
  components: !include packages/components/cwww-light.yaml
...
