---
substitutions:
  name: feeder
  friendly_name: Feeder
  ip: '10.0.1.245'

packages:
  base: !include packages/base.yaml
  device: !include packages/devices/shelly-1.yaml
  component: !include
    file: packages/components/feeder.yaml
    vars:
      output: relay0
...
