---
substitutions:
  friendly_name: Front Porch
  name: front-porch-light
  ip: '10.0.1.139'

packages:
  base: !include packages/base.yaml
  device: !include packages/devices/shelly-duo.yaml
  component: !include packages/components/cwww-light.yaml
...
