---
substitutions:
  friendly_name: Garage Door
  name: garage-door
  ip: '10.0.1.52'

packages:
  base: !include packages/base.yaml
  device: !include packages/devices/shelly-1.yaml
  component: !include
    file: packages/components/garage-door.yaml
    vars:
      output: relay0
      switch: switch0
...
