---
substitutions:
  friendly_name: Guest Bathroom Light Switch
  name: guest-bathroom-light-switch
  ip: '10.0.1.105'

packages:
  base: !include packages/base.yaml
  device: !include packages/devices/cf-swm1.yaml
  component0: !include packages/components/restart-button.yaml
  component1: !include
    file: packages/components/detached-button.yaml
    vars:
      button: button0
      relay: relay0
      target: light.guest_bathroom
  component2: !include
    file: packages/components/on-long-hold.yaml
    vars:
      button: button0
      action: button.press
      target: restart_button
...
