---
substitutions:
  friendly_name: Guest Bathroom 2
  name: guest-bathroom-light-2
  ip: '10.0.1.8'

packages:
  base: !include packages/base.yaml
  devices: !include packages/devices/shelly-duo.yaml
  components: !include packages/components/cwww-light.yaml
...
