---
substitutions:
  friendly_name: Guest Bedroom Fan
  name: guest-bedroom-fan
  ip: '10.0.1.7'

packages:
  base: !include packages/base.yaml
  device: !include packages/devices/shelly-1.yaml
  component: !include
    file: packages/components/binary-fan.yaml
    vars:
      output: relay0
...
