---
substitutions:
  friendly_name: Guest Bathroom 3
  name: guest-bathroom-light-3
  ip: '10.0.1.148'

packages:
  base: !include packages/base.yaml
  devices: !include packages/devices/shelly-duo.yaml
  components: !include packages/components/cwww-light.yaml
...
