---
substitutions:
  friendly_name: Guest Bedroom
  name: guest-bedroom-light
  ip: '10.0.1.104'

packages:
  base: !include packages/base.yaml
  device: !include packages/devices/shelly-1.yaml
  component: !include packages/components/binary-light.yaml
...
