---
substitutions:
  friendly_name: Guest Bathroom Vanity Light 2
  name: guest-bathroom-vanity-light-2
  ip: '10.0.1.8'

packages:
  base: !include packages/base.yaml
  device: !include packages/devices/shelly-duo.yaml
  component: !include
    file: packages/components/cwww-light.yaml
    vars:
      cold_white: cold_white
      warm_white: warm_white
...
