---
substitutions:
  friendly_name: Guest Bedroom
  name: guest-bedroom-fan
  ip: '10.0.1.7'

packages:
  base: !include packages/base.yaml
  devices: !include packages/devices/shelly-1.yaml
  components: !include packages/components/binary-fan.yaml
...
