---
substitutions:
  friendly_name: Guest Bedroom Light
  name: guest-bedroom-light
  ip: '10.0.1.104'

packages:
  base: !include packages/base.yaml
  device: !include packages/devices/shelly-1.yaml
  component: !include
    file: packages/components/binary-light.yaml
    vars:
      output: output0
...
