---
substitutions:
  friendly_name: Guest Bathroom 1
  name: guest-bathroom-light-1
  ip: '10.0.1.180'

packages:
  base: !include packages/base.yaml
  devices: !include packages/devices/shelly-duo.yaml
  components: !include packages/components/cwww-light.yaml
...
