---
substitutions:
  friendly_name: Hallway Light 1
  name: hallway-light-1
  ip: '10.0.1.225'

packages:
  base: !include packages/base.yaml
  device: !include packages/devices/kauf-blf15.yaml
  component: !include
    file: packages/components/rgbww-light.yaml
    vars:
      red: red
      green: green
      blue: blue
      cold_white: cold_white
      warm_white: warm_white
...
