---
substitutions:
  friendly_name: Hallway 1
  name: hallway-light-1
  ip: '10.0.1.225'

packages:
  base: !include packages/base.yaml
  devices: !include packages/devices/shelly-duo.yaml
  components: !include packages/components/cwww-light.yaml
...
