---
substitutions:
  friendly_name: Hallway Light 1
  name: hallway-light-1
  ip: '10.0.1.115'

packages:
  base: !include packages/base.yaml
  device: !include packages/devices/shelly-vintage-a19.yaml
  component: !include
    file: packages/components/monochromatic-light.yaml
    vars:
      brightness: brightness
...
