---
substitutions:
  friendly_name: Hallway 2
  name: hallway-light-2
  ip: '10.0.1.187'

packages:
  base: !include packages/base.yaml
  device: !include packages/devices/shelly-duo.yaml
  component: !include packages/components/cwww-light.yaml
...
