---
substitutions:
  friendly_name: Kitchen 2
  name: kitchen-light-2
  ip: '10.0.1.13'

packages:
  base: !include packages/base.yaml
  devices: !include packages/devices/shelly-duo.yaml
  components: !include packages/components/cwww-light.yaml
...
