---
substitutions:
  friendly_name: Kitchen 1
  name: kitchen-light-1
  ip: '10.0.1.161'

packages:
  base: !include packages/base.yaml
  devices: !include packages/devices/shelly-duo.yaml
  components: !include packages/components/cwww-light.yaml
...
