---
substitutions:
  friendly_name: Kitchen Light 3
  name: kitchen-light-3
  ip: '10.0.1.6'

packages:
  base: !include packages/base.yaml
  device: !include packages/devices/shelly-duo.yaml
  component: !include
    file: packages/components/cwww-light.yaml
    vars:
      cold_white: cold_white
      warm_white: warm_white
...
