---
substitutions:
  friendly_name: Living Room Proxy
  name: living-room-proxy
  ip: '10.0.1.189'

packages:
  base: !include packages/base.yaml
  device: !include packages/devices/atom-lite.yaml
  component0: !include packages/components/proxy.yaml
  component1: !include
    file: packages/components/dht11.yaml
    vars:
      dht11_pin: GPIO33
...
