---
substitutions:
  friendly_name: Living Room Proxy
  name: living-room-proxy
  ip: '10.0.1.189'

packages:
  base: !include packages/base.yaml
  device: !include packages/devices/esp32-proxy.yaml
  component: !include packages/components/proxy.yaml
...
