---
substitutions:
  friendly_name: Living Room Light Switch
  name: living-room-light-switch
  ip: '10.0.1.226'

packages:
  base: !include packages/base.yaml
  device: !include packages/devices/cf-swm1.yaml
  component0: !include
    file: packages/components/completely-detached-button.yaml
    vars:
      button: button0
      target: light.living_room
...
