---
substitutions:
  friendly_name: Living Room
  name: living-room-light
  ip: '10.0.1.217'

packages:
  base: !include packages/base.yaml
  devices: !include packages/devices/shelly-duo.yaml
  components: !include packages/components/cwww-light.yaml
...
