---
substitutions:
  friendly_name: Master Bathroom Vanity 6
  name: master-bathroom-vanity-light-6
  ip: '10.0.1.128'

packages:
  base: !include packages/base.yaml
  devices: !include packages/devices/shelly-duo.yaml
  components: !include packages/components/cwww-light.yaml
...
