---
substitutions:
  friendly_name: Master Bedroom
  name: master-bedroom-light
  ip: '10.0.1.9'

packages:
  base: !include packages/base.yaml
  device: !include packages/devices/shelly-duo.yaml
  component: !include packages/components/cwww-light.yaml
...
