---
substitutions:
  friendly_name: Master Bathroom Vanity 5
  name: master-bathroom-vanity-light-5
  ip: '10.0.1.157'

packages:
  base: !include packages/base.yaml
  devices: !include packages/devices/shelly-duo.yaml
  components: !include packages/components/cwww-light.yaml
...
