---
substitutions:
  friendly_name: Master Bedroom Light
  name: master-bedroom-light
  ip: '10.0.1.127'

packages:
  base: !include packages/base.yaml
  device: !include packages/devices/kauf-blf15.yaml
  component: !include
    file: packages/components/rgbww-light.yaml
    vars:
      red: red
      green: green
      blue: blue
      cold_white: cold_white
      warm_white: warm_white
...
