---
substitutions:
  friendly_name: Master Bathroom Vanity 2
  name: master-bathroom-vanity-light-2
  ip: '10.0.1.130'

packages:
  base: !include packages/base.yaml
  device: !include packages/devices/shelly-duo.yaml
  component: !include packages/components/cwww-light.yaml
...
