---
substitutions:
  friendly_name: Master Bedroom Fan
  name: master-bedroom-fan
  ip: '10.0.1.199'

packages:
  base: !include packages/base.yaml
  device: !include packages/devices/shelly-1.yaml
  component: !include
    file: packages/components/binary-fan.yaml
    vars:
      output: output0
...
