---
substitutions:
  friendly_name: Master Bedroom
  name: master-bedroom-fan
  ip: '10.0.1.199'

packages:
  base: !include packages/base.yaml
  devices: !include packages/devices/shelly-1.yaml
  components: !include packages/components/binary-fan.yaml
...
