---
substitutions:
  friendly_name: Master Bathroom
  name: master-bathroom-light
  ip: '10.0.1.147'

packages:
  base: !include packages/base.yaml
  devices: !include packages/devices/shelly-1.yaml
  components: !include packages/components/binary-light.yaml
...
