---
substitutions:
  friendly_name: Master Bedroom Proxy
  name: master-bedroom-proxy
  ip: '10.0.1.70'
  dht11_pin: GPIO13

packages:
  base: !include packages/base.yaml
  device: !include packages/devices/esp32.yaml
  component0: !include packages/components/proxy.yaml
  component1: !include packages/components/dht11.yaml
...
