---
substitutions:
  friendly_name: Master Bathroom Vanity 3
  name: master-bathroom-vanity-light-3
  ip: '10.0.1.156'

packages:
  base: !include packages/base.yaml
  devices: !include packages/devices/shelly-duo.yaml
  components: !include packages/components/cwww-light.yaml
...
