---
substitutions:
  friendly_name: Master Bedroom Light
  name: master-bedroom-light
  ip: '10.0.1.243'

packages:
  base: !include packages/base.yaml
  device: !include packages/devices/shelly-vintage-a19.yaml
  component: !include
    file: packages/components/monochromatic-light.yaml
    vars:
      brightness: brightness
...
