---
substitutions:
  friendly_name: Master Bathroom
  name: master-bathroom-fan
  ip: '10.0.1.105'

packages:
  base: !include packages/base.yaml
  device: !include packages/devices/shelly-1.yaml
  component: !include packages/components/binary-fan.yaml
...
