---
substitutions:
  friendly_name: Office
  name: office-light
  ip: '10.0.1.166'

packages:
  base: !include packages/base.yaml
  devices: !include packages/devices/shelly-duo.yaml
  components: !include packages/components/cwww-light.yaml
...
