---
substitutions:
  friendly_name: Office Proxy
  name: office-proxy
  ip: '10.0.1.189'

packages:
  base: !include packages/base.yaml
  device: !include packages/devices/atom-lite.yaml
  component0: !include packages/components/proxy.yaml
...
