---
substitutions:
  friendly_name: Office Lamp Button
  name: office-lamp-button
  ip: '10.0.1.98'

packages:
  base: !include packages/base.yaml
  device: !include packages/devices/shelly-1.yaml
  component0: !include packages/components/restart-button.yaml
  component1: !include
    file: packages/components/detached-button.yaml
    vars:
      button: switch0
      relay: relay0
      target: light.office
  component2: !include
    file: packages/components/on-long-hold.yaml
    vars:
      button: switch0
      action: button.press
      target: restart_button
...
