---
substitutions:
  friendly_name: Thermostat
  name: thermostat
  ip: '10.0.1.169'

packages:
  base: !include packages/base.yaml
  device: !include packages/devices/atom-lite.yaml
  component0: !include packages/components/proxy.yaml
  component1: !include
    file: packages/components/dht11.yaml
    vars:
      dht11_pin: GPIO32
  component2: !include
    file: packages/components/heat-pump.yaml
    vars:
      yellow: GPIO22
      orange: GPIO19
      white: GPIO23
      green: GPIO33
...
