---
substitutions:
  friendly_name: Thermostat
  name: thermostat
  ip: '10.0.1.169'
  dht11_pin: GPIO13

packages:
  base: !include packages/base.yaml
  device: !include packages/devices/aitrip-esp32-devkit-v1.yaml
  component0: !include packages/components/ble-tracker-hub.yaml
  component1: !include packages/components/proxy.yaml
  component2: !include
    file: packages/components/dht11.yaml
    vars:
      dht11_pin: GPIO13
  component: !include
    file: packages/components/heat-pump.yaml
    vars:
      orange: GPIO25
      white: GPIO26
      green: GPIO27
      yellow: GPIO33
...
