---
substitutions:
  friendly_name: Utility Room
  name: utility-room-light
  ip: '10.0.1.149'

packages:
  base: !include packages/base.yaml
  device: !include packages/devices/shelly-1.yaml
  component: !include packages/components/binary-light.yaml
...
