# Provides binary output `relay0` and binary sensor `button0`
---
substitutions:
  device_name: CloudFree Switch

esphome:
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

output:
  - platform: gpio
    pin: GPIO1
    id: relay0

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      inverted: true
    id: button0
    internal: true
...
