# Provides binary output `relay0` and binary sensors `button0`, `motion0`, and
# `lux0`
---
substitutions:
  device_name: CloudFree Motion Switch

esp8266:
  board: esp01_1m

output:
  - platform: gpio
    pin: GPIO12
    id: relay0

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
    id: button0
    internal: true
  - platform: gpio
    pin:
      number: GPIO5
      inverted: true
    name: "Motion"
    id: motion0
    device_class: motion
  - platform: gpio
    pin: GPIO14
    name: "Lux"
    id: lux0
    device_class: light
...
