# Provides binary output `relay0` and binary sensor `button0`
---
substitutions:
  device_name: CloudFree Switch

esp32:
  board: esp32-c3-devkitm-1

output:
  - platform: gpio
    pin: GPIO1
    id: relay0

binary_sensor:
  - platform: gpio
    pin: GPIO3
    id: button0
    internal: true
...
