# Provides float outputs `red`, `green`, `blue`, `cold_white`, and `warm_white`
---
substitutions:
  device_name: Kauf A15 RGBWW Bulb

esp8266:
  board: esp01_1m

output:
  - platform: esp8266_pwm
    id: red
    pin: GPIO4
  - platform: esp8266_pwm
    id: green
    pin: GPIO12
  - platform: esp8266_pwm
    id: blue
    pin: GPIO14
  - platform: esp8266_pwm
    id: cold_white
    pin: GPIO5
  - platform: esp8266_pwm
    id: warm_white
    pin: GPIO13
...
