# Provides float outputs `red`, `green`, `blue`, `cold_white`, and `warm_white`
# Provides substitutions `$cw_temp` and `$ww_temp`
---
substitutions:
  device_name: Kauf A15 RGBWW Bulb
  cw_temp: 6500 K
  ww_temp: 2700 K

esp8266:
  board: esp01_1m

output:
  - platform: esp8266_pwm
    id: red
    pin: GPIO4
  - platform: esp8266_pwm
    id: green
    pin: GPIO12
  - platform: esp8266_pwm
    id: blue
    pin: GPIO14
  - platform: esp8266_pwm
    id: cold_white
    pin: GPIO5
  - platform: esp8266_pwm
    id: warm_white
    pin: GPIO13
...
