---
esp8266:
  board: esp01_1m
  restore_from_flash: true

output:
  - platform: gpio
    pin: GPIO4
    id: relay0

binary_sensor:
  - platform: gpio
    pin: 5
    id: sensor
    internal: true
...
