# Provides float outputs `cold_white` and `warm_white`
# Provides substitutions `$cw_temp` and `$ww_temp`
---
substitutions:
  device_name: Shelly Duo
  cw_temp: 6500 K
  ww_temp: 2700 K

esp8266:
  board: esp01_1m

output:
  - platform: esp8266_pwm
    id: warm_white
    pin: GPIO4
    min_power: 0.0005
    zero_means_zero: true
  - platform: esp8266_pwm
    id: cold_white
    pin: GPIO5
    min_power: 0.0005
    zero_means_zero: true
...
