# Provides binary output `output0` and binary sensor `switch0`
---
esp8266:
  board: esp01_1m

output:
  - platform: gpio
    pin: GPIO4
    id: output0

binary_sensor:
  - platform: gpio
    pin: GPIO5
    id: switch0
    internal: true
...
