---
sensor:
  - platform: dht
    model: DHT11
    pin: $dht11_pin
    temperature:
      id: dht11_temperature
      name: "${friendly_name} Temperature"
    humidity:
      name: "${friendly_name} Humidity"
    update_interval: 2s
...
