# Expects pin `$dht11_pin`
# Provides temperature sensor `dht11_temperature`
# and provides humidity sensor `dht11_humidity`
---
sensor:
  - platform: dht
    model: DHT11
    pin: $dht11_pin
    temperature:
      id: dht11_temperature
      name: "${friendly_name} Temperature"
    humidity:
      id: dht11_humidity
      name: "${friendly_name} Humidity"
    update_interval: 2s
...
