# Expects action `$action`, target `$target`,  and binary sensor `$button`
---
binary_sensor:
# This seems to be behavior which was *supposed* to work, however currently
# it does not. Until this is fixed, we'll have to create a new binary sensor.
# - id: !extend $button
  - platform: template
    id: btn_replace_me_when_fixed
    internal: true
    lambda: 'return id($button).state;'
    on_click:
      - min_length: 10s
        max_length: 60s
        then:
          - $action: $target
...
