# Expects float outputs `$red`, `$green`, `$blue`, `$cold_white`, and `$warm_white`
# Expects color temperatures `$cw_temp` and `$ww_temp`
---
binary_sensor:
  - platform: status
    # When API gets disconnected, the light needs to be turned on.
    on_release:
      - light.turn_on: rgbww_light

light:
  - platform: rgbww
    # Name is set in packages/base/esphome.yaml
    # https://esphome.io/components/esphome#esphome-configuration-variables
    name: None
    id: rgbww_light
    red: $red
    green: $green
    blue: $blue
    cold_white: $cold_white
    warm_white: $warm_white
    cold_white_color_temperature: $cw_temp
    warm_white_color_temperature: $ww_temp
    restore_mode: ALWAYS_ON
    default_transition_length: 200ms
    flash_transition_length: 200ms
...
