# Expects action `action`, target `target`,  and binary sensor `switch`
---
binary_sensor:
# This seems to be behavior which was *supposed* to work, however currently
# it does not. Until this is fixed, we'll have to create a new binary sensor.
# - id: !extend $switch
  - platform: template
    id: switch_replace_me_when_fixed
    internal: true
    lambda: 'return id($switch).state;'
    on_state:
      - $action: $target
...
